"""empty message

Revision ID: 3f356b362501
Revises: 34a8f24d46e9
Create Date: 2016-10-10 23:14:31.700847

"""

# revision identifiers, used by Alembic.
revision = '3f356b362501'
down_revision = '34a8f24d46e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.String(length=50), nullable=True),
    sa.Column('lng', sa.String(length=50), nullable=True),
    sa.Column('cmd', sa.String(length=1000), nullable=True),
    sa.Column('bus_route', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usersx')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersx',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chatid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('lat', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lng', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cmd', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('bus_route', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'usersx_pkey')
    )
    op.drop_table('users')
    ### end Alembic commands ###
