"""empty message

Revision ID: 5687e4f528b9
Revises: 3f356b362501
Create Date: 2016-10-10 23:15:06.432812

"""

# revision identifiers, used by Alembic.
revision = '5687e4f528b9'
down_revision = '3f356b362501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chatid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('lat', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lng', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cmd', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('bus_route', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')
    )
    ### end Alembic commands ###
