"""empty message

Revision ID: f356dacee05c
Revises: af24f6f6a0c7
Create Date: 2016-10-10 22:53:06.424697

"""

# revision identifiers, used by Alembic.
revision = 'f356dacee05c'
down_revision = 'af24f6f6a0c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.String(length=50), nullable=True),
    sa.Column('lng', sa.String(length=50), nullable=True),
    sa.Column('cmd', sa.String(length=1000), nullable=True),
    sa.Column('bus_route', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chatid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('lat', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lng', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cmd', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('bus_route', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')
    )
    op.drop_table('users2')
    ### end Alembic commands ###
